repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/PyCQA/pylint.git
    rev: v4.0.5
    hooks:
    -   id: pylint
        name: pylint (python 3)
        language_version: python3
        additional_dependencies:
        - requests>=2.32.0
        args:
        -  --load-plugins=pylint.extensions.redefined_variable_type,pylint.extensions.bad_builtin
-   repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
    -   id: black
        language_version: python3
